config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  get :profile, to: 'users#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  enum rule: {
    first_attempt_passed?: 'first_attempt_passed?',
    all_tests_for_level?: 'all_tests_for_level?',
    all_tests_for_category?: 'all_tests_for_category?'
  }.freeze

  mount_uploader :logo, LogoUploader

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :rule, :description, presence: true
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.badge_created')
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: t('.badge_updated')
    else
      render :edit
    end
  end

  def destroy
    redirect_to admin_badges_path, notice: t('.badge_deleted') if @badge.destroy
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params
      .require(:badge)
      .permit(:name, :logo, :description, :rule, :rule_value, :remove_logo)
  end
end

app/helpers/admin/badges_helper.rb
# frozen_string_literal: true

module Admin::BadgesHelper
  def badges_rules
    Badge.rules.keys.map { |symbol| [I18n.t(".badge_rules.#{symbol}"), symbol] }
  end

  def show_all_categories_with_ids
    Category.all.map { |category| "#{category.id} - #{category.title}" }
  end
end

app/views/admin/badges/_badge.html.erb
<tbody>
  <tr>
    <td><%= badge.name %></td>
    <td><%= image_tag badge.logo_url %></td>
    <td><%= badge.description %></td>
    <td><%= I18n.t(".badge_rules.#{badge.rule}") %></td>

    <td class="align-middle">
      <%= link_to t('links.show'),
                  admin_badge_path(badge),
                  class: 'btn btn-primary' %>
    </td>

    <td class="align-middle">
      <%= link_to t('links.edit'),
                  edit_admin_badge_path(badge),
                  class: 'btn btn-primary' %>
    </td>

    <td class="align-middle">
      <%= link_to t('links.delete'),
                  admin_badge_path(badge),
                  method: :delete,
                  data: { confirm: t('links.are_you_sure') },
                  class: 'btn btn-danger' %>
    </td>
  </tr>
</tbody>

app/views/admin/badges/_form.html.erb
<div class="card border-primary">
  <div class="card-body">
    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <%= render 'shared/errors', resource: @badge %>

      <div class="form-group">
        <p>
          <b><%= form.label :name %></b>
          <%= form.text_field :name, id: :name, class: 'form-control' %>
        </p>

        <p>
          <b><%= form.label :logo %></b>
          <p>
            <%= image_tag @badge.logo_url if @badge.logo? %>
            <%= form.file_field :logo %>
          </p>
        </p>

        <p>
          <%= form.label :remove_logo %>
          <%= form.check_box :remove_logo %>
        </p>

        <p>
          <b><%= form.label :description %></b>
          <%= form.text_area :description, class: 'form-control' %>
        </p>

        <p>
          <b><%= form.label :rule %></b>
          <%= form.select :rule, badges_rules, selected: @badge.rule %>
        </p>

        <p>
          <b><%= form.label :rule_value %></b>
          <%= form.text_field :rule_value, id: :rule_value, class: 'form-control' %>
        </p>

        <p>
          <%= form.submit t(".#{action_name}_badge"), class: "btn btn-success" %>
          <%= link_to t('links.back'), admin_badges_path, class: 'btn btn-primary' %>
        </p>

        <h6>
          <b> * </b>
          <p> 1. <%= t('.level_rule') %></p>
          <p> 2. <%= t('.category_rule') %></p>
        </h6>

        <p>
          <%= form.label :categories_list %>
          <%= form.select :categories_list, show_all_categories_with_ids %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h2 class="text-center"><b><%= t('.header', badge_name: @badge.name) %></b></h2>

    <%= render 'form' %>
  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-12">
    <h1><%= t('.header') %></h1>

    <%= render 'shared/errors', resource: @badge %>

    <p>
      <%= link_to t('.new_badge_button'), new_admin_badge_path, class: 'btn btn-success' %>
      <%= link_to t('links.back'), admin_tests_path, class: 'btn btn-primary' %>
    </p>

    <table class="table" style="text-align: center">
      <thead class="thead-light">
        <tr>
          <th scope="col"><%= t('.name') %></th>
          <th scope="col"><%= t('.logo') %></th>
          <th scope="col"><%= t('.description') %></th>
          <th scope="col"><%= t('.rule') %></th>
          <th scope="col" colspan="3"><%= t('.actions') %></th>
        </tr>
      </thead>

      <%= render @badges %>
    </table>
  </div>
</div>

app/views/admin/badges/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h2 class="text-center"><b><%= t('.header') %></b></h2>

    <%= render 'form' %>
  </div>
</div>

app/views/admin/badges/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h2 class="text-center"><b><%= t('.header', badge_name: @badge.name) %></b></h2>

    <div class="card border-primary mb-3">
      <div class="card-body">
        <div class="form-group">
          <p>
            <b><%= t('.logo') %></b>
            <%= image_tag @badge.logo_url %>
          </p>

          <p>
            <b><%= t('.description') %></b>
            <%= @badge.description %>
          </p>

          <p>
            <b><%= t('.rule') %></b>
            <%= I18n.t(".badge_rules.#{@badge.rule}") %>
          </p>
        </div>
      </div>
    </div>

    <p>
      <%= link_to t('.edit_badge_button'), edit_admin_badge_path(@badge), class: 'btn btn-success' %>
      <%= link_to t('links.delete'),
                  admin_badge_path(@badge),
                  method: :delete,
                  data: { confirm: t('links.are_you_sure') },
                  class: 'btn btn-danger' %>
      <%= link_to t('links.back'), admin_badges_path, class: 'btn btn-primary' %>
    </p>
  </div>
</div>