config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  get :profile, to: 'users#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :gist_url, presence: true
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

class Admin::GistsController < Admin::BaseController
  before_action :set_gists, only: :index
  before_action :set_gist, only: :destroy

  def index; end

  def destroy
    @gist.destroy

    redirect_to admin_gists_path, notice: t('.gist_deleted')
  end

  private

  def set_gists
    @gists = Gist.all
  end

  def set_gist
    @gist = Gist.find(params[:id])
  end
end

app/helpers/admin/gists_helper.rb
# frozen_string_literal: true

module Admin::GistsHelper
  def fetch_gist_hash_from_url(url)
    url.split('/').last
  end
end

app/views/admin/gists/_gist.html.erb
<tbody>
  <tr>
    <td><%= link_to truncate(gist.question.body, length: 25), admin_question_path(gist.question) %></td>
    <td><%= link_to fetch_gist_hash_from_url(gist.gist_url), gist.gist_url, target: '_blank' %></td>
    <td><%= gist.user.email %></td>

    <td class="align-middle">
      <%= link_to t('links.delete'),
                  admin_gist_path(gist),
                  method: :delete,
                  data: { confirm: t('links.are_you_sure') },
                  class: 'btn btn-danger' %>
    </td>
  </tr>
</tbody>

app/views/admin/gists/index.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-12">
    <h2><%= t('.header') %></h2>

    <p><%= link_to t('links.back'), admin_tests_path, class: 'btn btn-primary' %></p>

    <table class="table" style="text-align: center">
      <thead class="thead-light">
        <tr>
          <th scope="col"><%= t('.question') %></th>
          <th scope="col"><%= t('.link_to_github') %></th>
          <th scope="col"><%= t('.author') %></th>
          <th scope="col"><%= t('.action') %></th>
        </tr>
      </thead>

      <%= render @gists %>
    </table>
  </div>
</div>