config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  get :profile, to: 'users#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test, touch: true
  has_many :answers, dependent: :destroy
  has_many :test_passages, foreign_key: 'current_question_id', dependent: :nullify, inverse_of: :current_question
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  SUCCESS_PERCENTAGE = 85

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true, inverse_of: :test_passages

  before_validation :set_next_question

  scope :by_user_id, ->(user_id) { where(user_id: user_id) }
  scope :successfully_passed, -> { where('result >= ?', SUCCESS_PERCENTAGE) }

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    finish_passage! if self.test.with_timer? && time_is_over?
    self.result = percent_result

    save!
  end

  def completed?
    current_question.nil?
  end

  def current_question_number
    test.questions.where('id <= ?', current_question.id).count
  end

  def success?
    percent_result >= SUCCESS_PERCENTAGE
  end

  def percent_result
    correct_questions * 100 / questions_count
  end

  def passage_progress
    100 / questions_count * (current_question_number - 1)
  end

  def questions_count
    test.questions.count
  end

  private

  def set_next_question
    self.current_question = if new_record?
                              test.questions.order(:id).first if test.present?
                            else
                              # Disabling the Rubocop's rule is just to save this studying example of the code.
                              test.questions.order(:id).where('id > ?', current_question&.id).first
                            end
  end

  def correct_answer?(answer_ids)
    return unless answer_ids

    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def finish_passage!
    self.current_question = nil
  end

  def time_is_over?
    finish_at = created_at + self.test.passage_time

    Time.current >= finish_at
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]

  def show; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      SendCompletedTestEmailJob.set(wait: 5.seconds).perform_later(@test_passage)

      assigned_badges = Badges::AssignBadgesService
                          .new(test_passage: @test_passage, current_user: current_user)
                          .fetch_assigned_badges

      if assigned_badges.any?
        SendAchievedBadgeEmailJob.set(wait: 20.seconds).perform_later(assigned_badges, current_user)
      end

      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def result; end

  def gist
    result = Gists::CreateGistQuestionService.new(question: @test_passage.current_question).call

    if result.success?
      gist = gist_create(result.html_url)

      flash[:notice] = t('.success', url: view_context.link_to(t('links.gist'),
                                                               gist.gist_url,
                                                               target: '_blank',
                                                               rel: 'noopener'))
    else
      flash[:alert] = t('.failure')
    end

    redirect_to @test_passage
  end

  private

  def gist_create(url)
    Gist.create!(
      question: @test_passage.current_question,
      gist_url: url,
      user: current_user
    )
  end

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
# frozen_string_literal: true

module TestPassagesHelper
  def result_message(test_passage)
    test_passage.success? ? t('test_passages.result.success') : t('test_passages.result.failure')
  end

  def green_red(test_passage)
    test_passage.success? ? 'green' : 'red'
  end

  def time_left(test_passage)
    test = test_passage.test

    return unless test.with_timer?

    Time.zone.at(test_passage.created_at + test.passage_time - Time.current).strftime('%s')
  end
end

app/views/test_passages/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="card">
    <div class="card-header">
      <h2><%= t('.header') %><u><%= @test_passage.test.title %></u></h2>
    </div>

    <div class="card-body">
      <b><%= t('.test_result') %></b>
      <span class="passage-result <%= green_red(@test_passage) %>">
        <%= @test_passage.percent_result %> %
        <p><h3><b><u><%= result_message(@test_passage) %></u></b></h3></p>
      </span>

      <p><%= link_to t('.tests_button'), tests_path, class: 'btn btn-primary' %></p>
    </div>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="row justify-content-center mt-3">
  <div class="card">
    <div class="card-header">
      <h1><%= t('.header', test_title: @test_passage.test.title) %></h1>
    </div>

    <p class="card-text ml-2">
      <%= t('.number', current: @test_passage.current_question_number, total: @test_passage.questions_count) %>
    </p>

    <p>
      <b class="card-text ml-2"><%= @test_passage.current_question.body %></b>
    </p>

    <div class="card-body">
      <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
        <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <p>
            <%= b.check_box id: "answer_ids_#{b.object.id}" %>
            <%= b.label %>
          </p>
        <% end %>

        <p><%= form.submit t('.next_button'), class: 'btn btn-primary' %></p>
        <p><%= link_to t('.gist_question'), gist_test_passage_path(@test_passage), method: :post, class: 'btn btn-info' %></p>
      <% end %>
    </div>

    <% if @test_passage.test.with_timer? %>
      <div class="timer-left-time ml-2">
        <b><%= "#{ t('.time_left') }" %></b>
        <%= content_tag :div, "#{ t('.start') }", class: 'timer', data: { timer: time_left(@test_passage) } %>
      </div>
    <% end %>

    <%= content_tag :div, class: 'progress test-passage-progress', data: { percent: @test_passage.passage_progress } do %>
      <div class="progress-bar progress-bar-striped bg-success" role="progressbar">
        <%= @test_passage.passage_progress %> %
      </div>
    <% end %>
  </div>
</div>