config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  get :profile, to: 'users#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: %i[index destroy]
    resources :badges
  end

  resources :feedbacks, only: %i[new create]
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.try(:id) } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>
    </h2>

    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, sanitize(message, tags: %w(a p), attributes: %w(href target)), class: "alert alert-#{ApplicationHelper::FLASH_MESSAGE_STYLE[key.to_sym]}" %>
<% end %>

app/views/shared/_footer.html.erb
<div class="text-center mt-4 mb-2">
  <footer class="blockquote-footer">
    <div>
      <%= link_to t('links.feedback'), new_feedback_path %><br>
      <%= t('.git_hub_repo') %><%= github_url('georgiybykov', 'test-guru') %> | <%= project_lifetime %>
    </div>

    <div>
      <%= t('.author') %> |
      <%= link_to t('.project_link'), 'https://thinknetica.com', target: '_blank' %>
    </div>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <span class="navbar-text">
    <%= link_to t('nav.project_title'), root_path, class: 'navbar-brand' %>

    <% if current_user&.admin? %>
      | <%= link_to t('nav.admin_panel'), admin_tests_path, class: 'navbar-brand' %>
    <% end %>
  </span>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('nav.greeting') %><b><%= greeting_in_header %></b>! |
      <b><%= link_to t('links.profile'), profile_path %></b> |
      <%= link_to t('links.log_out'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('links.log_in'), new_user_session_path %> |
      <%= link_to t('links.sign_up'), new_user_registration_path %>
    <% end %>
  </span>
</nav>